### ISSUE TITLE
Shadow size too big

### ISSUE THREAD

**Issue by Akira1San** [leiget/Godot_FPC_Base#1]
I think its best to lower the shadow size in the settings.

**Comment by leiget** [comment]
Since this is project is for showing how a FPC might work in Godot the graphics don't really matter. I havn't had any problems with the shadows on my Linux machine. Having any problems on your end, like any glitches? Is it just the resolution being too high or low?

I've lowered the resolution back down to 4096. I forgot I put it up to 8K.

**Comment by Akira1San** [comment]
Thx, it just gives more fps. Great documented tut. :)
